# Numpy

In [33]:
import numpy as np

In [34]:
width = [32.4, 41.7, 23.5, 30.2, 28.9]
length = [75.3, 69.4, 67.3, 88.9, 93.4]

In [35]:
type(width)

list

In [36]:
area = width*length

TypeError: can't multiply sequence by non-int of type 'list'

In [37]:
np_length = np.array(length)
np_width = np.array(width)

In [39]:
type(np_length)

numpy.ndarray

In [40]:
area= np_length*np_width

In [41]:
area

array([2439.72, 2893.98, 1581.55, 2684.78, 2699.26])

In [42]:
is_area_2500 = area > 2500

In [43]:
sum(is_area_2500)

3

In [44]:
np_combined = np.array([length,width])

In [45]:
np_combined

array([[75.3, 69.4, 67.3, 88.9, 93.4],
       [32.4, 41.7, 23.5, 30.2, 28.9]])

In [46]:
np_combined.shape

(2, 5)

In [47]:
np_combined[0][1]

69.4

In [48]:
np_combined[:,2]

array([67.3, 23.5])

In [49]:
np.mean(np_combined[1,:])

31.339999999999996

In [50]:
np.median(np_combined[1,:])

30.2

In [51]:
np_combined

array([[75.3, 69.4, 67.3, 88.9, 93.4],
       [32.4, 41.7, 23.5, 30.2, 28.9]])

In [52]:
np.corrcoef(np_combined[0,:],np_combined[1,:])

array([[ 1.        , -0.18636923],
       [-0.18636923,  1.        ]])

In [53]:
np.std(np_combined[0,:])

10.46911648612241

In [54]:
np.random.randint(0,11,(2,2,5))

array([[[ 2,  4,  9,  7,  6],
        [ 1,  9,  9,  9, 10]],

       [[ 6,  9,  5,  9,  5],
        [ 8,  8,  0,  5, 10]]])

In [55]:
length = np.random.normal(100,5,100)
width = np.random.normal(50,20,100)

In [56]:
np_area = np.column_stack((length,width))

In [57]:
np_area

array([[100.77990575,  60.81263366],
       [ 99.21053157,  40.20282855],
       [101.04634177,  61.44097924],
       [ 99.57941171,  67.52613049],
       [ 99.74110976,  41.87800941],
       [ 98.86124632,  63.5372137 ],
       [103.53103933,  66.2928938 ],
       [ 96.8693276 ,  45.13612532],
       [ 97.36192988,  41.8974978 ],
       [ 99.16531357,  70.62873599],
       [ 96.01723067,  54.08691606],
       [100.58065057,  70.87218355],
       [100.24051867,  56.90771336],
       [ 98.0950064 ,  69.02583994],
       [102.9752678 ,  62.53195614],
       [101.48711313,  53.36215801],
       [ 87.80188529,  55.3549599 ],
       [ 90.25267207,  15.85308676],
       [ 98.74743994,  35.20100901],
       [ 94.52087803,  56.40003159],
       [ 87.58858724,  79.90863592],
       [103.90034918,  48.71971688],
       [105.1154516 ,  44.62178752],
       [ 98.12952798,  55.90174941],
       [101.96657765,  28.91356253],
       [101.69895607,  37.800471  ],
       [103.71735458,  86.28133295],
 

In [58]:
range(0,10)

range(0, 10)

In [59]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.ones(10)*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [62]:
np.random.seed(102)

In [63]:
np.random.normal(50,20,100)

array([ 8.33613659e+01,  6.85172363e+01,  7.11599355e+01,  3.15932197e+01,
        7.59949693e+01,  5.66236602e+01,  3.98031006e+01,  3.19380216e+01,
        4.73996725e+01,  5.23593017e+00,  6.94632976e+01,  4.95163038e+01,
        4.03014449e+01,  2.78147128e+01,  3.88205047e+01,  7.08477315e+01,
        1.57547459e+01,  5.27223977e+01,  4.07111202e+01,  5.10195968e+01,
        7.89579742e+01,  6.18627695e+01,  3.48876863e+01,  3.74566893e+01,
        6.76806977e+01,  5.32543551e+01, -5.62573101e-02,  5.82158198e+01,
        6.45750081e+01,  5.05828040e+01,  4.41789508e+01,  5.62858615e+01,
        6.99437937e+01,  1.18571259e+02,  3.84286530e+01,  4.59167399e+01,
        1.26566269e+01,  7.88686789e+01,  5.80676007e+01,  3.61846920e+01,
        7.34457493e+01,  1.85774319e+01,  6.60398462e+01,  3.85605428e+01,
        8.10678742e+01,  6.40243996e+01,  7.02998535e+01,  4.76391607e+01,
        2.87221811e+01,  7.35338240e+01,  7.69523888e+01,  3.41139991e+01,
        2.44011394e+01,  

In [64]:
np.random.normal(50,20,100)

array([ 55.57885096,  48.71224344,  75.49958936,  68.25006509,
        46.27176729,  51.17545855,  65.78968821,  69.59650139,
        -3.01669672,  43.8746062 ,  35.6054104 ,  52.34788773,
        40.75117907,  31.18913327,  14.42028093,  60.58774477,
        66.62703831,  44.82709046,  53.3454799 ,  38.12216843,
        38.73859829,  67.65610468,  56.22989286,  33.1140409 ,
        66.67924655,  77.83848971,  58.63318094,  61.55360679,
        60.66033859,  64.29694585,  44.65544195,  73.96772576,
        89.42389668,  44.70987429,  44.1458013 ,  18.49204011,
        58.77968861,  46.01593587,  53.18567826,  76.07408723,
        50.03634263, -15.48928341,  62.04174279,  46.40230616,
        19.88859966,  55.48681705,  79.37250267,  72.42264124,
        85.99681919,  97.03483745,  65.1362742 ,  47.4793029 ,
        68.9041924 ,  67.08504078,  14.58404942,  73.96836269,
        23.81433497,  76.30716571,  68.46195035,  53.28005373,
        67.08202044,  23.84802451,  20.28096095,  67.41